# See COPYING for license.

# A Dockerfile for development outside of Debian 8 :)
#
# docker build -f Dockerfile.dev -t primecoin-dev .
# docker run -v /full/path/to/code:/primecoin-debian --rm primecoin-dev
# < write tests, fix errors >
# docker run -v /full/path/to/code:/primecoin-debian --rm primecoin-dev
# < write tests, fix errors >
# ... repeat ;)

FROM debian:8

RUN apt-get update -y
RUN apt-get install -y \
    build-essential \
    libboost-all-dev \
    libdb++-dev \
    libjson-spirit-dev \
    libleveldb-dev \
    libssl-dev \
    qt4-dev-tools

VOLUME ["/primecoin-debian"]
WORKDIR /primecoin-debian

CMD cd src && make test
